#!/usr/bin/env sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Abort the script on errors and unbound variables.
set -o nounset      # Abort on unbound variable.
# set -o xtrace       # Set debugging.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object.
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Run linters.
exec yarn commitlint --edit $1
